### PR TITLE
Add a toggle between home and trip planner views

### LINKED ISSUE #12: Add a navbar to toggle between home and trip planner views
We are going to have a separate link for trip planner in navbar. So that people can go and forth between trip planner and our home page where we show weather forecast.

### PR DESCRIPTION
**Pull request by arpitBhalla**
closes #12

### CODE REVIEW

**Review by Ruchita1010 — CHANGES_REQUESTED** [review]
The toggle button looks good and works properly!
And please resolve the merge conflicts

**Review by Ruchita1010 — APPROVED** [review]

**Comment by sumana2001** [comment]
Hey @arpitBhalla  why have you deleted App.js? Isn't it better to have the routes for the two pages in app.js instead of routes.js. It changes a lot of files which is not actually needed. What do you think?😊

**Comment by arpitBhalla** [comment]
It's in screens dir as `home.js`, and another file for trip planner as `trip.js`, maybe it'd be easier to work with separate file instead of single App.js with home and planner? I haven't changed the content so wouldn't make much efforts to resolve conflicts?

**Comment by sumana2001** [comment]
@arpitBhalla What I meant was what is the need of route.js file if you can do the same in App.js. You wouldn't have needed to change index.js also because of that. Having two pages is ofcourse necessary for home and trip but I am talking about the route.js. Also could you tell me what you changed in index.html? Seems like the entire file is changed, but can't find which line

**Comment by arpitBhalla** [comment]
Yep, we can do that.

**Pull request merged**
